### ISSUE TITLE
Add sounds

### ISSUE THREAD

**Issue by tammojan** [tammojan/modeltelescoop#1]
Smilde: radio
Zon: noise
Pulsar: ticks
Moon: PI9CAM + echo
...

**Comment by tammojan** [comment]
Needs #9

**Comment by stefanlinden** [comment]
Do we want background music as well?

**Comment by stefanlinden** [comment]
Working in the `sounds` branch. We can merge with master, but I'll try to add some more sounds first.

**Comment by tammojan** [comment]
Ah I'll try! No, we do not want background music (sound isolation is not working very well in the hub).

**Comment by stefanlinden** [comment]
Okay, I removed the (groovy) background music. 😛

**Comment by tammojan** [comment]
I added a more relevant sound for the Moon.
